### PR TITLE
Fix: Removes infinite loop in getCamps request on Camp List table

### PR DESCRIPTION
**Pull request by dhmi19**
## Notion ticket link

Spontaneous bug fix for inifinite loop of getCamps request

## Implementation description
* 

## Steps to test
1. Open the camp list page and go to inspect element -> network tab 
2. Verify that the request to get all camps is not being repeatedly called

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by williamtran10 — APPROVED** [review]
LGTM. Fixes it when I run it locally. Any idea why specifically this fixes it?

**Review by e-wai — APPROVED** [review]
Yep, looks good. I assume the fix for the footer will be another PR?

**Comment by dhmi19** [comment]
> Yep, looks good. I assume the fix for the footer will be another PR?

what's wrong with the footer?

**Comment by e-wai** [comment]
Sorry, think I'm thinking of CampDetails - the useEffect PATCH request?

**Comment by dhmi19** [comment]
> Sorry, think I'm thinking of CampDetails - the useEffect PATCH request?

yeah that would be another PR I think. it's not really the same bug/issue

**Pull request merged**
