### PR TITLE
Change toast styling to subtle

### PR DESCRIPTION
**Pull request by e-wai**
## Implementation description
* Design request

## Steps to test
-> setup one of the buttons as a demo

```ts
toast({
  description:
    "Registration link has been sent and they will be notified.",
  status: "success",
  variant: "subtle",
  duration: 3000,
});

toast({
  description:
    "Registration link has been sent and they will be notified.",
  status: "info",
  variant: "subtle",
  duration: 3000,
});

toast({
  description:
    "Registration link has been sent and they will be notified.",
  status: "warning",
  variant: "subtle",
  duration: 3000,
});

toast({
  description:
    "Registration link has been sent and they will be notified.",
  status: "error",
  variant: "subtle",
  duration: 3000,
});
```

https://user-images.githubusercontent.com/40974372/193250176-45f2445d-ea86-4abe-a402-996fe6cc17f8.mov

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by dhmi19 — COMMENTED** [review]
Do we also need to change the toasts in the WaitlistTable file?

**Comment by e-wai** [comment]
Yeah good call - going to wait for design input to check this is what we want

**Comment by dhmi19** [comment]
> 

Will review again after this change is made

**Comment by e-wai** [comment]
@dhmi19 proposing that we merge this for now, it's a bandaid fix for design that does address the main interaction change they wanted (shorter, no closing X) 

Did some quick exploration into the custom background stylings on Toast and had issues:
- `containerStyles` didn't change the actual background colour, because it's a wrapper around Alert which relies on the variant tags to map to a color scheme
- Played around with something like https://stackoverflow.com/questions/69531448/how-to-change-the-background-color-of-the-chakra-ui-toast-component but no success yet

**Review by dhmi19 — APPROVED** [review]
tested all the toasts and they render for 3 seconds as expected. styling is a tad bit off but we can revisit at another point

**Pull request merged**
