### PR TITLE
Feat: Implement change user role to access control table

### PR DESCRIPTION
**Pull request by AmandaMisjuwar**
## Notion ticket link

[Access Management: Change User Role](https://www.notion.so/uwblueprintexecs/Access-Management-Change-User-Role-52f1f83dcba04aa6a27400298ba900f8)

## Implementation description
* Add functionality to change a user's role from FON Admin -> Camp Coordinator and vice versa

## Steps to test
1. Log in as an Admin and go to the Access Control table
2. Select a user to change a role in the row's dropdown
3. Upon successful change, a success toast message should appear.
4. Go to MongoDB and make sure the change is reflected in the DB

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by dhmi19 — APPROVED** [review]
tested and looks good to merge for me

**Comment by dhmi19** [comment]
We might need to rebase this branch to keep it updated with the initial table, search + filters code. I think I requested for some changes which are not here but were included in the previous PR

**Comment by AmandaMisjuwar** [comment]
> We might need to rebase this branch to keep it updated with the initial table, search + filters code. I think I requested for some changes which are not here but were included in the previous PR

I think there was one requested change I didn't make for the sake of readability - do you know which ones aren't included? This branch is based off main after merging the first ticket for the table @dhmi19

**Comment by dhmi19** [comment]
> > We might need to rebase this branch to keep it updated with the initial table, search + filters code. I think I requested for some changes which are not here but were included in the previous PR
> 
> I think there was one requested change I didn't make for the sake of readability - do you know which ones aren't included? This branch is based off main after merging the first ticket for the table @dhmi19

Ahh it's ok, I can't remember now and it's not super important anyways. I think we're good to merge since there doesn't seem to be any conflicts with the main branch

**Pull request merged**
